### ISSUE TITLE
dance r, negative zero

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#9]
Slider for rho: the value shown just above the slider is, I think, always .00 for zero, never -.00. But the value displayed to the right of the slider is sometimes .00, sometimes -.00. Would it be possible to make it always .00? Thanks

**Comment by gfmoore** [comment]
Well, that was a weird one and was due to how JavaScript uses IEEE 754 (Floating point spec) to represent numbers. Zero might not be zero, but a very very small number (positive or negative) It may be something to be aware of if when using zero you find something not quite right!!!! (It's the way that numbers can never be perfectly represented when using a fixed number of binary digits to represent numbers - you need an infinite number of bits to do it properly. Most languages have a typed variable called int or long. JavaScript is untyped and represents any number as a floating point number as accurately as it can, but by the 14th decimal place or so it might have lost some accuracy. 

Anyway, for this I added some code to force rho to zero (0.0)  if it's absolute value was less than 0.0001. It should be okay now.

**Comment by gdcumming** [comment]
1.1.3

I get it. Nice fix. Closing...
